#handle dependencies and project settings
[tool.poetry]
name="atuomate-youtube-with-crewai"
version="0.1.0"
description="Autome Youtube tasks with crewai"
authors=["Nur Memeti" <memetinur93@gmail.com>]
[tool.poetry.dependencies]
python= ">=3.10.0,<3.12"
crewai={extras=["tools"],version="^0.19.0}
pydantic="^2.6.3"
load-dotenv="^0.1.0"
crewai-tools="0.0.15"

[tool.pyright]
#
useLibraryCodeForTypes=true
excldue=[".cache"]

[tool.ruff]
select=['E','W','F','I','B','C4','ARG','SIM']
ignore=['W291','W292','W293']

[build-system]
